CREATE TYPE VALID_LEVEL AS ENUM('Trainee', 'Junior', 'Middle', 'Senior');

CREATE TABLE if not exists worker (
	ID bigserial PRIMARY KEY NOT NULL,
	NAME VARCHAR(1000) CHECK(LENGTH(NAME)>1),
	BIRTHDAY DATE CHECK(BIRTHDAY>'1900-01-01'),
	LEVEL VALID_LEVEL NOT NULL,
	SALARY int CHECK(SALARY>100) CHECK(SALARY<10000)
);

CREATE TABLE if not exists client (
	ID bigserial PRIMARY KEY NOT NULL,
	NAME VARCHAR(1000) CHECK(LENGTH(NAME)>1) NOT NULL
);

CREATE TABLE IF NOT EXISTS project (
	ID bigserial PRIMARY KEY NOT NULL,
	CLIENT_ID bigserial,
	START_DATE DATE,
	FINISH_DATE DATE,
	FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(id)
);

CREATE TABLE if not exists project_worker (
	PROJECT_ID bigserial,
	WORKER_ID bigserial,
	PRIMARY KEY (PROJECT_ID, WORKER_ID),
    FOREIGN KEY(PROJECT_ID) REFERENCES project(ID),
    FOREIGN KEY (WORKER_ID) REFERENCES worker(ID)
);